"""add interfaces table

Revision ID: 172e602748b4
Revises: 00ee365424ce
Create Date: 2026-07-06 19:17:57.524504
"""

from alembic import op
import sqlalchemy as sa


revision = '172e602748b4'
down_revision = '00ee365424ce'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interfaces',
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('if_index', sa.Integer(), nullable=False),
    sa.Column('if_name', sa.String(length=150), nullable=True),
    sa.Column('if_alias', sa.String(length=255), nullable=True),
    sa.Column('if_descr', sa.String(length=255), nullable=True),
    sa.Column('mac_address', sa.String(length=50), nullable=True),
    sa.Column('speed', sa.BigInteger(), nullable=True),
    sa.Column('mtu', sa.Integer(), nullable=True),
    sa.Column('admin_status', sa.String(length=30), nullable=True),
    sa.Column('oper_status', sa.String(length=30), nullable=True),
    sa.Column('rx_octets', sa.BigInteger(), nullable=True),
    sa.Column('tx_octets', sa.BigInteger(), nullable=True),
    sa.Column('rx_errors', sa.BigInteger(), nullable=True),
    sa.Column('tx_errors', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_interfaces_device_id_devices'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interfaces'))
    )
    op.create_index(op.f('ix_interfaces_admin_status'), 'interfaces', ['admin_status'], unique=False)
    op.create_index(op.f('ix_interfaces_device_id'), 'interfaces', ['device_id'], unique=False)
    op.create_index(op.f('ix_interfaces_id'), 'interfaces', ['id'], unique=False)
    op.create_index(op.f('ix_interfaces_if_index'), 'interfaces', ['if_index'], unique=False)
    op.create_index(op.f('ix_interfaces_if_name'), 'interfaces', ['if_name'], unique=False)
    op.create_index(op.f('ix_interfaces_is_deleted'), 'interfaces', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_interfaces_oper_status'), 'interfaces', ['oper_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interfaces_oper_status'), table_name='interfaces')
    op.drop_index(op.f('ix_interfaces_is_deleted'), table_name='interfaces')
    op.drop_index(op.f('ix_interfaces_if_name'), table_name='interfaces')
    op.drop_index(op.f('ix_interfaces_if_index'), table_name='interfaces')
    op.drop_index(op.f('ix_interfaces_id'), table_name='interfaces')
    op.drop_index(op.f('ix_interfaces_device_id'), table_name='interfaces')
    op.drop_index(op.f('ix_interfaces_admin_status'), table_name='interfaces')
    op.drop_table('interfaces')
    # ### end Alembic commands ###